id: P1DA6C3D9
initial_creation_type: input
source_metadata:
  title: Ten Royal Sūtras
  language: zh
  description: 'A collection related to the ten royal sūtras or ten sūtras of the
    king (rgyal po''i mdo bcu), which are said to have been translated upon the advice
    of Padmasambhava for Emperor Tri Songdetsen''s daily recitation:'
  volume:
    0d241907dd4846558ff55f18cfcad865:
      title: Outline of the Ten Royal Sūtras
      parent: Outlines
    845427caef074ca099879fefc14ce4f3:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtras
    c6ba96d558c94f9091738377c781da78:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Sūtras
    1a95754dccd340e1be3ea13d105f81d6:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtras
    da911c0085e1444f9cc84c1b0ca6ed2c:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtras
    44a2d884d80d4257a0d2ba07aefb0e98:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sūtras
    0e8fb445c1d24fd68f8bad79cffc594f:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Sūtras
    d17f29c338234e578f1e752e41520281:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtras
    85ce4077f58d436e8776e85203ef71cf:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtras
    c26e920ffe5f4e2e82c60cb48750e3cc:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtras
    940eb6c964084bb7aa19e8a44cc2abff:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Sūtras
created_at: '2022-03-01T06:06:38.015577'
last_modified_at: '2022-03-01T06:06:38.015579'
